name: Lighthouse Audit

on:
  workflow_dispatch:

jobs:
    generate_lighthouse_audit:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Audit preview URL with Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v3
        with:
            urls: |
              https://www.rap.ru
            uploadArtifacts: true
            temporaryPublicStorage: true
